server:
  port: 5000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IvanKyrylov/config-repo.git
          clone-on-start: true

  security:
    user:
      name: root
      password: root
